spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      springframework: info
      jdbc:
        datasource:
          DataSourceTransactionManager: DEBUG
      jetbrains:
        exposed:
          SpringTransactionManager: DEBUG